version: '3'
services:
  core:
    image: 'sgb:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core
    tty: true
    volumes:
      - ./core:/core
    environment:
      PYTHONWARNINGS: 'ignore'
    restart: unless-stopped

  iam-service:
    image: 'sgb:latest'
    tty: true
    container_name: iam-service
    depends_on:
      - core
    volumes:
      - ./iam:/iam
    environment:
      PYTHONWARNINGS: 'ignore'
    restart: always
    working_dir: /iam
    ports:
      - '53001:53001'

  iam:
    image: 'sgb:latest'
    tty: true
    container_name: iam
    depends_on:
      - core
      - iam-service
    volumes:
      - ./iam:/iam
    environment:
      PYTHONWARNINGS: 'ignore'
    restart: always
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    working_dir: /iam
    ports:
      - '8000:8000'

  sgb:
    image: 'sgb:latest'
    tty: true
    container_name: sgb
    depends_on:
      - core
    volumes:
      - ./SouthGermanBank:/SouthGermanBank
    environment:
      PYTHONWARNINGS: 'ignore'
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8001"
    restart: always
    working_dir: /SouthGermanBank
    ports:
      - '8001:8001'
