version: '3'
services:
  core:
    image: 'akatsuki:latest'
    build: .
    container_name: core
    tty: true
    volumes:
      - ./core:/core
    environment:
      PYTHONWARNINGS: 'ignore'
    restart: always


  iam:
    image: 'akatsuki:latest'
    tty: true
    container_name: iam
    depends_on:
      - core
    volumes:
      - /iam:/iam
    environment:
      PYTHONWARNINGS: 'ignore'
    restart: always

  sgb:
    image: 'akatsuki:latest'
    tty: true
    container_name: sgb
    depends_on:
      - core
    volumes:
      - /SouthGermanBank:/SouthGermanBank
    environment:
      PYTHONWARNINGS: 'ignore'
    restart: always
