version: '3.4'
services:

  iam-service:
    image: 'banking:development'
    build:
      context: .
    tty: true
    container_name: banking-iam-service
    volumes:
      - ./iam:/iam
    restart: always
    command: >
      bash -c "python3 manage.py run_grpc_server '[::]:50051'"
    working_dir: /iam
#    ports:
#      - '50051:50051'

  sgb-service:
    image: 'banking:development'
    build:
      context: .
    tty: true
    container_name: banking-sgb-service
    volumes:
      - ./sgb:/sgb
    restart: always
    working_dir: /sgb
#    ports:
#      - '50052:50052'

  iam:
    image: 'banking:development'
    build:
      context: .
    tty: true
    container_name: banking-iam
    depends_on:
      - iam-service
    volumes:
      - ./iam:/iam
    restart: always
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --no-input --clear &&
               python manage.py runserver 0.0.0.0:8000"
    working_dir: /iam
    ports:
      - '8000:8000'

  sgb:
    image: 'banking:development'
    build:
      context: .
    tty: true
    container_name: banking-sgb
    depends_on:
      - iam-service
      - sgb-service
    volumes:
      - ./sgb:/sgb
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --no-input --clear &&
               python manage.py runserver 0.0.0.0:8001"
    restart: always
    working_dir: /sgb
    ports:
      - '8001:8001'
