version: '3'
services:
  core:
    image: 'akatsuki:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core
    tty: true
    volumes:
      - ./core:/core
    command: sh -c "pip install -e core_dir/core/"

    environment:
      PYTHONWARNINGS: 'ignore'
    restart: unless-stopped

  iam:
    image: 'akatsuki:latest'
    tty: true
    container_name: iam
    depends_on:
      - core
#      - iam-service
    volumes:
      - ./iam:/iam
    environment:
      PYTHONWARNINGS: 'ignore'
    restart: always
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    working_dir: /iam
    ports:
      - '8000:8000'

#  iam-service:
#    image: 'akatsuki:latest'
#    tty: true
#    container_name: iam-service
#    depends_on:
#      - core
#    volumes:
#      - ./iam:/iam
#    environment:
#      PYTHONWARNINGS: 'ignore'
#    restart: always
#    command: >
#      bash -c "python manage.py makemigrations &&
#               python manage.py migrate &&
#               python manage.py runserver 0.0.0.0:8000"
#    working_dir: /iam
#    ports:
#      - '53001:53001'


  sgb:
    image: 'akatsuki:latest'
    tty: true
    container_name: sgb
    depends_on:
      - core
    volumes:
      - ./SouthGermanBank:/SouthGermanBank
    environment:
      PYTHONWARNINGS: 'ignore'
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8001"
    restart: always
    working_dir: /SouthGermanBank
    ports:
      - '8001:8001'
