FROM ubuntu:20.04

RUN apt-get update && apt-get install -y python3.10

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1

RUN python --version

WORKDIR aaa_codebase/

ADD core/



