# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HelloWorld.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10HelloWorld.proto\" \n\x0cHelloRequest\x12\x10\n\x08Greeting\x18\x01 \x01(\t\"$\n\nHelloReply\x12\x16\n\x0eReturnGreeting\x18\x01 \x01(\t2\xba\x01\n\x07Greeter\x12(\n\x08personal\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12(\n\x06parrot\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x30\x01\x12(\n\x06\x63hatty\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00(\x01\x12\x31\n\rbidirectional\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HelloWorld_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=20
  _HELLOREQUEST._serialized_end=52
  _HELLOREPLY._serialized_start=54
  _HELLOREPLY._serialized_end=90
  _GREETER._serialized_start=93
  _GREETER._serialized_end=279
# @@protoc_insertion_point(module_scope)
