# Generated by Django 4.1 on 2023-11-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='password',
        ),
    ]
